### ISSUE TITLE
Adding build tags to git repo

### ISSUE THREAD

**Issue by mattseymour** [cokelaer/fitter#16]
I have noticed that the project does not include any git-tags related to the builds (as found in Pypi) it would be really helpful if you could tag builds so they correspond to pypi release versions.

If you need any help in doing this I would be more than willing to help you out. There does not seem to be too many versions so it should be a fairly quick process.

Thanks
Matt

[@_mseymour](https://twitter.com/_mseymour)

**Comment by cokelaer** [comment]
Dear Matt, I have release a new version on pypi. I have added a release within this github repo (tag 1.2)

**Comment by mattseymour** [comment]
Awesome thanks for your help. 👍
