### ISSUE TITLE
Takes too long to finish a fitting

### ISSUE THREAD

**Issue by linrl3** [cokelaer/fitter#20]
It seems like Fitter try many models in Scipy to fit my data and it takes too long. Is there a better using of Fitter to finish the job?

**Comment by bluetyson** [comment]
Specify a few distributions that you think might be relevant?
Or take a subset of your data if it is large?

Also, thanks very much for the package, very useful!

**Comment by cokelaer** [comment]
Indeed, the simplest is to down sample your data. Fitting is quite robust and 10,000 data points even a thousand are usually enough to get a good feeling of which distributions is the best one. I am currently updating the documentation, which should include a FAQs with this question/solution. thanks for using fitter.
