### ISSUE TITLE
Env. anaconda

### ISSUE THREAD

**Issue by AlessandroMinervini** [cokelaer/fitter#21]
Is possible install the package with anaconda? (pyhton 3.7)

**Comment by oschwengers** [comment]
Hi @AlessandroMinervini , just install it via `python3 -m pip install fitter` within your conda env.

**Comment by cokelaer** [comment]
It is currently building for py3.7 on pypi. It will be available on conda with py3.7 for the next release. You may want to update the bioconda recipes.
