### ISSUE TITLE
fitter-1.3.0 use pip install got error message

### ISSUE THREAD

**Issue by OscarMCY** [cokelaer/fitter#30]
(base) C:\Users\233Desktop>pip install C:\Users\233Desktop\Downloads\fitter-1.3.0.tar.gz
Processing c:\users\233desktop\downloads\fitter-1.3.0.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\233Desktop\anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\233Desktop\\AppData\\Local\\Temp\\pip-req-build-olrsvmrt\\setup.py'"'"'; __file__='"'"'C:\\Users\\233Desktop\\AppData\\Local\\Temp\\pip-req-build-olrsvmrt\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\233Desktop\AppData\Local\Temp\pip-pip-egg-info-1e1s8o9g'
         cwd: C:\Users\233Desktop\AppData\Local\Temp\pip-req-build-olrsvmrt\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\233Desktop\AppData\Local\Temp\pip-req-build-olrsvmrt\setup.py", line 41, in <module>
        long_description = open("README.rst").read(),
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 3273: illegal multibyte sequence
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by cokelaer** [comment]
hard to reproduce for me. Tests are performed under Linux indeed. I'll keep this open in case someone may help

**Comment by 723373214** [comment]
update your pip version may help.

**Comment by ErnestDong** [comment]
I think #46 can fix. It's a Chinese only bug :(

**Comment by jhkjhkim** [comment]
this bug happens on Korean too :(

**Comment by cokelaer** [comment]
@OscarMCY indeed this was a reported and fixed bug in #46
