### ISSUE TITLE
Timeout error for all distributions.

### ISSUE THREAD

**Issue by henriquedgarcia** [cokelaer/fitter#31]
Hello guys. Thank you for this very useful tool.

I am using Fitter with python 3.8 and in my last use I noticed a timeout error for all distributions with a dataset of only 8 thousand values. I've been using Fitter for almost a year and this error has never happened before.

Searching deeply in fitter.py file, I found on [line 426](https://github.com/cokelaer/fitter/blob/4dc8f1caf884fad3abd8fb8224af032b9462de06/src/fitter/fitter.py#L426), in the method `_timed_run()`, the `it` object is calling the `.isAlive()` method, however, the `InterruptableThread` class that inherits the `thread.Thread` class has only the `.is_alive()` method. Changing `.isAlive()` to `.is_alive()` fixes this for me.

Without this, when the code reaches here, the program raises an error captured by line 292 `except Exception:` in the `_fit_single_distribution()` method and announces a timout error.

Thanks again and sorry for the bad english.

**Comment by tirkarthi** [comment]
I have created https://github.com/cokelaer/fitter/pull/32 to fix this. `isAlive` was a deprecated alias to `is_alive` and was removed in Python 3.9 in PR https://github.com/python/cpython/pull/15225.

Thanks

**Comment by cgmAether** [comment]
I also Encountered this error in Python 3.9. 
[Pull Request](https://github.com/cokelaer/fitter/pull/32) solved it for me.

**Comment by kmedved** [comment]
I also encountered this error. Every distribution fails due to a "(taking more than 30 seconds)" error.

**Comment by miguelcarcamov** [comment]
I also encountered this error. Nice that I could find this. Please make it public on pypi

**Comment by notbanker** [comment]
Upvoting the inclusion of this fix

**Comment by guerrajorge** [comment]
I am still seeing the error, even after the fix. It is weird because I do not see it with the repo example but I see it when I use my own data. I tried different timeouts but It is definitely not taking using those timeouts. Any suggestions?

**Comment by cgmAether** [comment]
> I am still seeing the error, even after the fix. It is weird because I do not see it with the repo example but I see it when I use my own data. I tried different timeouts but It is definitely not taking using those timeouts. Any suggestions?

If you've made the fix of changing .isAlive() to .is_alive() and you still have timeouts for every distribution. I would assume that they are valid timeouts occurring as a result of your dataset being very large or hard to fit. How big is your dataset? @guerrajorge

**Comment by guerrajorge** [comment]
I was thinking the same thing but I tried very long timeouts and it would give me the timeout error right away (it is not even accounting for the change). There are 25791 rows (~0.412656MB). I also changed the default time and it is giving me the error right away. The default example on the main repo is not working either, even when I specify the "lambda" distribution.
