### ISSUE TITLE
NOT clearing the output of summary()

### ISSUE THREAD

**Issue by dulti** [cokelaer/fitter#33]
It would be nice if there were an option (a parameter to summary()?) to not clear the output of the jupyter cell, i.e. to stop the execution of the line
`pylab.clf()`
The reason being, I'm running a fitting of several variables in a loop and I want to examine the output in one cell, instead of either repeating the process manually for all my variables or saving the Fitted instances to, say, a list, and then still making n cells and manually call list[f].summary() for each f.

**Comment by cokelaer** [comment]
Done in version 1.4.0. One issue is that legends will accumulate the calls but you can go around by redoing the legend:

```from scipy import stats
data = stats.gamma.rvs(2, loc=1.5, scale=2, size=10000)

from fitter import Fitter
f = Fitter(data, timeout=3000, distributions=['gamma', 'rayleigh', 'uniform']) #Increasing time out time
f.fit()
f.summary()
f.summary()


# here just to get the names of the distributions
df = f.summary(clf=False)
# and create the legend
legend(df.index)
```

**Comment by cokelaer** [comment]
Now in the git repository
