### ISSUE TITLE
Empty progress bar is shown when progress=False

### ISSUE THREAD

**Issue by msat59** [cokelaer/fitter#36]
Hi.

The progress bar object is created in the class init section, but its actual use is in `fit()` method. As a result, an empty progress bar is shown if it's not used; `f.fit(progress=False)`. It is shown in the image below.

![image](https://user-images.githubusercontent.com/20813541/120651375-00e79600-c47f-11eb-9f02-1e661e41d891.png)

The fix is initializing the progress bar in the `fit()` method. I will submit the PR soon.

**Comment by cokelaer** [comment]
Thanks a lot for this PR. This is now incorporated.
