### ISSUE TITLE
Improve logging facilities

### ISSUE THREAD

**Issue by MadRabbit05** [cokelaer/fitter#50]
Hi,
Why do logging module is directly use to display info/warning instead of logger variable created with logging.getLogger()?
What is the solution to disable fitter logging if fitter is used in other module ?
I update fitter code from logging.info() to logger.info() (line 300 and 310 of fitter.py) and now i can force the logging level in my other module.
But I'm not sure that's the best way to control the logging level of other module. 
Thanks for that so usefull module :-)

**Comment by cokelaer** [comment]
@MadRabbit05 thank to @negodfre whose PR has just been merged to fix this issue. I'll put a release 1.5.2 on pypi very soon
