### ISSUE TITLE
Conda package not updated

### ISSUE THREAD

**Issue by LSgeo** [cokelaer/fitter#51]
The bioconda channel only has up to version 1.2.3 available. Note that the current latest version includes several bug fixes, and you will need to either install via pip, or edit the source directly to make some things work.

**Comment by epruesse** [comment]
See https://github.com/bioconda/bioconda-recipes/pull/24094 - just need to work out why the package is failing its build there and it'll update in Bioconda.

**Comment by cokelaer** [comment]
looks like it is fixed. @epruesse thanks for reporting this issue on bioconda
