### ISSUE TITLE
Progress Bar in Jupyter lab

### ISSUE THREAD

**Issue by diegourreamendez** [cokelaer/fitter#61]
I have a problem with Jupyter lab progress bar not displaying correctly. I've searched, but I can't find a way to fix it. Any solution? Does anyone else have that problem?

![Screenshot_2](https://user-images.githubusercontent.com/64099015/186661322-fb16a4e8-25b5-4b4a-a3a0-701caa671222.png)

**Comment by cokelaer** [comment]
Should be fixed in v1.5.1 now on pypi

**Comment by TY-Cheng** [comment]
any method to suppress the progress bar? sorry i'm not familiar with tqdm; i set logger so the progress bar wont go into my log file but it keeps going into cli and made the stdout file huge:
![image](https://user-images.githubusercontent.com/14033617/193756524-00ce5386-2af2-4793-a9c1-5b307755d86b.png)

![image](https://user-images.githubusercontent.com/14033617/193756355-ce5a6c44-14f4-4175-869e-112bfce0bba3.png)
seems the arg 'progress' is not functioning in the fit() function; any other method to manage it? thx.
