### ISSUE TITLE
quadbacy.py warning and skipping

### ISSUE THREAD

**Issue by EkremSel** [cokelaer/fitter#68]
With the below code:

```
f=Fitter(spread)
f.fit()
f.summary()
```

I am getting these warnings.  Is the fitter skipping because it deems it unnecessary? And the second warning appeared recently. Is it only calculating for 50 distributions now? 

Fitting 109 distributions:   0%|                                                               | 0/109 [00:00<?, ?it/s]WARNING:root:SKIPPED _fit distribution (taking more than 30 seconds)
Fitting 109 distributions:  14%|███████▍                                              | 15/109 [00:03<00:37,  2.54it/s]WARNING:root:SKIPPED loguniform distribution (taking more than 30 seconds)
WARNING:root:SKIPPED rv_histogram distribution (taking more than 30 seconds)
Fitting 109 distributions:  16%|████████▍                                             | 17/109 [00:06<01:20,  1.14it/s]WARNING:root:SKIPPED rv_continuous distribution (taking more than 30 seconds)
WARNING:root:SKIPPED reciprocal distribution (taking more than 30 seconds)
Fitting 109 distributions:  97%|███████████████████████████████████████████████████▌ | 106/109 [00:26<00:00,  3.77it/s]WARNING:root:SKIPPED kappa4 distribution (taking more than 30 seconds)
WARNING:root:SKIPPED levy_stable distribution (taking more than 30 seconds)
Fitting 109 distributions:  99%|████████████████████████████████████████████████████▌| 108/109 [00:33<00:00,  1.91it/s]WARNING:root:SKIPPED studentized_range distribution (taking more than 30 seconds)
Fitting 109 distributions: 100%|█████████████████████████████████████████████████████| 109/109 [00:35<00:00,  3.06it/s]

and 

:\Python310\lib\site-packages\scipy\integrate\_quadpack_py.py:1151: IntegrationWarning:

The maximum number of subdivisions (50) has been achieved.
  If increasing the limit yields no improvement it is advised to analyze 
  the integrand in order to determine the difficulties.  If the position of a 
  local difficulty can be determined (singularity, discontinuity) one will 
  probably gain from splitting up the interval and calling the integrator 
  on the subranges.  Perhaps a special-purpose integrator should be used.

C:\Python310\lib\site-packages\scipy\integrate\_quadpack_py.py:1151: IntegrationWarning:

The integral is probably divergent, or slowly convergent.

**Comment by cokelaer** [comment]
Fitter skips distribution fitting that take more than 30 seconds. Usually a sign of poor convergence. 
The second type of warning is new from scipy and also related to poor convergence as well indeed.

**Comment by EkremSel** [comment]
Thank you.
