### ISSUE TITLE
'module' object has no attribute 'sum' 

### ISSUE THREAD

**Issue by arima-sambunath** [cokelaer/fitter#7]
----------------------Code -------------
from scipy import stats
data = stats.gamma.rvs(2, loc=1.5, scale=2, size=100000)
from fitter import Fitter
f = Fitter(data, distributions=['gamma', 'rayleigh', 'uniform'])
f.fit()
## when I execute got this message

'module' object has no attribute 'sum'
SKIPPED gamma distribution (taking more than 10 seconds)
'module' object has no attribute 'sum'
SKIPPED rayleigh distribution (taking more than 10 seconds)
'module' object has no attribute 'sum'
SKIPPED uniform distribution (taking more than 10 seconds)

**Comment by cokelaer** [comment]
What version of scipy do you have ?
On my system (v0.17.1 of scipy), this example works well. 
I then tried with version 0.18.1 of scipy and could reproduce your problem. I increased the timeout to 20 seconds and then it works sometimes. So this is clearly related to the newest version of scipy that is far slower than the v0.17. In 0.17, the computation on your example takes less than a 1 second while with 0.18 it may exceed 20 seconds. 

I have forced the scipy version to be 0.17 in the setup requirements in the newest version of fitter package (1.0.7). If you still want to use version .0.18 of scipy, stick to fitter v1.0.6 and increase the timeout attribute:

    f.timeout = 20
    f.fit()

but I would not recommend it. Hopefully scipy will correct the issue in a newer version.

**Comment by cokelaer** [comment]
I do confirm the previous comments. Unfortunately, improvements in the scipy release 0.18 have made the default behaviour of the stats.<distribution>.fit function to be slower. One advantage mentionned is that it will converge more often...so I will increasee the timeout default behaviour from 10 to 30 seconds.

https://docs.scipy.org/doc/scipy/reference/release.0.18.0.html#scipy-optimize-improvements
