### ISSUE TITLE
I think BIC is defined incorrectly

### ISSUE THREAD

**Issue by helios1014** [cokelaer/fitter#77]
Looking at the code, BIC is defined as n * np.log(sq_error / n) + k * np.log(n).

I have traditionally seen it defined as -2 * loglik + k * log(n)

logLik is only used in your definition of aic and so I am confused as to what the source is for the formulation of  BIC you are using.

**Comment by cokelaer** [comment]
@helios1014 you right, the current version is specific to gaussian distribution but here we should use the more generic version indeed. I have changed the code and it should appear in v1.6.0
