### ISSUE TITLE
Fit distribution of discrete values

### ISSUE THREAD

**Issue by BishopKing** [cokelaer/fitter#79]
Hello guys,

I have a discrete list = [10, 30, 20, 3, 59, 99, 4, 120, 4].

I don't want to create a histrogram of this list as it will count the number of occurences.

What I want is that the list is used in order. Hence, on the y-axis the first value is 10, the next value is 30 etc. Based on this the data distribution should be determined. 

Is this possible?

**Comment by cokelaer** [comment]
what about the x-axis ? is this 1, 2, 3, 4 ... N ?
I believe that should be possible but is not implemented in the Fitter class for now. 

However, if you data is gaussian, you may try the HistFit function:

    from fitter import HistFit
    hf = HistFit(X=range(1, 10), 
        Y=np.array([10, 30, 20, 3, 59, 99, 4, 120, 4]))
    hf.fit(Nfit=1)

Ideally, the Fit function should be able to accept a density function indeed.
