### ISSUE TITLE
"bic" values not returned by summary()

### ISSUE THREAD

**Issue by kharelg1** [cokelaer/fitter#80]
I am not getting values for "bic" with the summary(). I am using the latest fitter version 1.5.2 with Python 3.9. Is there a fix to it?
![bic](https://user-images.githubusercontent.com/126341241/222432992-bec4963f-4f8e-4b8c-9b7c-13093a48d2df.PNG)

**Comment by cokelaer** [comment]
The output of the summary function is a pandas dataframe. You do not see the bic indeed in your example. However, as you may have notice you have ... between aic and ks_statistic. This means you have extra data there. 

This is the way pandas library works and I cannot do anything about it. This depends on your screen width and configuration. Howeve, you can access to it using e.g:

    df = myfit.summary()
    df['bic']

I recommend you to look at the pandas documentation for more information about dataframe manipulation.
