### ISSUE TITLE
AIC and BIC support

### ISSUE THREAD

**Issue by caiostringari** [cokelaer/fitter#9]
Hi,

Would you consider PR that implements AIC e BIC as comparison metrics in addition to SSE?

Cheers,

Caio

**Comment by cokelaer** [comment]
Hi,
Of course. It would be a good complement to the current implementation. 
thanks

**Comment by bartvanesWB** [comment]
That's a simple addition. I have added it in code, see attachment (change .txt to .py and run a compare script to see changes) ;)

[fitter.txt](https://github.com/cokelaer/fitter/files/2876185/fitter.txt)

**Comment by caiostringari** [comment]
Thank you very much! I also have an working implementation, but never had time to clean up the code and push it. I will have look at your implementation and if I have something else that could be added I let you guys know.

**Comment by bartvanesWB** [comment]
Had a look at your script and found an error, thanks for pointing your script out to me @caiostringari! Fixed it and added sorting based on AIC in plot_pdf-, get_best- and summary functions. Same as last time; change .txt to .py and run a compare script to see changes) ;)

[fitter.txt](https://github.com/cokelaer/fitter/files/2884778/fitter.txt)

**Comment by caiostringari** [comment]
Hi,

I implemented both AIC/BIC and Kullback-Leibler divergence metrics following what  bartvanesWB  did but I never had time to debug the code properly.

I will create a PR with what I did now.

Cheers,

Caio

**Comment by caiostringari** [comment]
The code seems to work fine. I used it for my PhD thesis without problems but I only ran a handful of tests. My PR faille to pass the Travis tests but I am not sure why. If you are in a hurry, maybe use my fork?

**Comment by cokelaer** [comment]
@caiostringari @mechaman I have now accepted the PR. Thanks a lot for this contribution. I will update a new version on pypi (v1.2)

**Comment by cokelaer** [comment]
available in v1.2
